*==============================================================================*
* clean_confounders.do
*
* GENERATED BY src/python/lmi/remote/make_partc_jobs.py
*           -- DO NOT EDIT BY HAND, REGENERATE
*
* Purpose : The proximity merge and the remaining personal confounders.
* Source  : 00013_data_clean.do:1002-1204
* Runs    : SOEPremote (soep-exec@diw.de)
* Depends : clean_citizenship_tc + clean_lingprox
* Saves   : $mydata/msuemer/clean_confounders
* Deviates: see the notes below
* Author  : Emre Suemer
*==============================================================================*
* ========================================================================
* PORT OF 00013_data_clean.do, PART C3 (orig lines 1002-1204)
* DOCUMENTATION, DO NOT SEND THIS PART
* ========================================================================
* Reads  $mydata/msuemer/clean_citizenship_tc + clean_lingprox
* Writes $mydata/msuemer/clean_confounders
*
* Do not send until the previous job's listing shows its .dta saved.
* A missing input does not halt a SOEPremote job.
*
* The proximity merge (orig :1002-1019) and the remaining personal
* confounders: education abroad, pre-migration work, pre-migration
* German, duration of stay, arrival with family, prior contacts,
* accommodation, health, trauma (orig :1022-1204).
* 
* Send only after BOTH clean_citizenship_tc and clean_lingprox report saved.
* 
* Deviations: keep/drop -> soepkeep/soepdrop; the foreach over the three
* pre-migration German items is unrolled, matching the Part A convention
* (macro substitution stays untested against the scanner and unrolling
* costs nothing analytically).
* ========================================================================

* ============ SEND FROM HERE DOWN (below your auth header) ============
use $mydata/msuemer/clean_citizenship_tc, clear
count
xtset pid syear

gen iso3_o = citizenship_iso_tc
replace iso3_o = "ALB" if iso3_o == "KOS"
replace iso3_o = "ISR" if iso3_o == "PSE"
merge m:1 iso3_o using $mydata/msuemer/clean_lingprox
soepdrop if _merge == 2
tabulate citizenship_iso_tc if _merge == 1
soepdrop _merge iso3_o

replace proxling2 = proxling2 * 100
gen ln_ling_proximity = ln(proxling2 + 1)
lab var ln_ling_proximity "ln of linguistic proximity to German"
rename proxling ling_proximity
lab var ling_proximity "linguistic proximity to German"
summarize ling_proximity ln_ling_proximity

rename lb0228 eduasl
clonevar years_sch0 = lb0187
replace years_sch0 = 0 if lb0183 == 2
recode years_sch0 .= 0 if lr3076 == 2
label variable years_sch0 "school: years of education abroad"
recode years_sch0 (-10/-1 = .)

rename lm0076i01 voc1yr
rename lm0076i08 voc1m
rename lm0076i02 voc2yr
rename lm0076i09 voc2m
rename lm0076i03 voc3yr
rename lm0076i10 voc3m
rename lm0076i04 uni1yr
rename lm0076i11 uni1m
rename lm0076i05 uni2yr
rename lm0076i12 uni2m
rename lm0076i06 phd1yr
rename lm0076i13 phd1m
rename lm0076i07 voc4yr
rename lm0076i14 voc4m

recode voc1yr voc1m voc2yr voc2m voc3yr voc3m uni1yr uni1m ///
    uni2yr uni2m phd1yr phd1m voc4m voc4yr (-5/-1 = .)

gen temp1 = voc1yr + voc1m/12
gen temp2 = voc2yr + voc2m/12
gen temp3 = voc3yr + voc3m/12
gen temp4 = voc4yr + voc4m/12
gen temp5 = uni1yr + uni1m/12
gen temp6 = uni2yr + uni2m/12
gen temp7 = phd1yr + phd1m/12
egen years_ausbhoch0 = rowtotal(temp1 temp2 temp3 temp4 temp5 ///
    temp6 temp7), missing
replace years_ausbhoch0 = 0 if eduasl == 2
lab var years_ausbhoch0 "voc/uni years of education abroad"

egen total_years_edu0 = rowtotal(years_sch0 years_ausbhoch0), missing
lab var total_years_edu0 "years of education before migration"
replace total_years_edu0 = . if years_sch0 >= .
replace total_years_edu0 = . if years_ausbhoch0 >= .
bysort pid (syear): carryforward total_years_edu0 years_sch0 ///
    years_ausbhoch0, replace
bysort pid (minusyear): carryforward total_years_edu0 years_sch0 ///
    years_ausbhoch0, replace

soepdrop temp1 temp2 temp3 temp4 temp5 temp6 temp7
soepdrop voc1yr voc1m voc2yr voc2m voc3yr voc3m
soepdrop uni1yr uni1m uni2yr uni2m phd1yr phd1m voc4m voc4yr

recode pgpsbila pgpbbila eduasl (-5/-1 = .)
bysort pid (syear): carryforward pgpsbila pgpbbila, replace
replace pgpsbila = 0 if eduasl == 2
xtsum total_years_edu0 years_sch0 years_ausbhoch0

gen work0 = 1 if lr3034 > 0 & lr3034 < .
recode work0 . = 0 if lb0248 == 1 | lr3032 == 1 | ///
    lr3033_v1 == 1 | lr3033_v2 == 1 | lr3033_h == 1
bysort pid (syear): carryforward work0, replace
bysort pid (minusyear): carryforward work0, replace
label variable work0 "worked before arrival"

gen speak_german0 = lm0128i01
replace speak_german0 = lb1231 if speak_german0 < 0 | speak_german0 >= .
gen write_german0 = lm0128i02
replace write_german0 = lb1232 if write_german0 < 0 | write_german0 >= .
gen read_german0 = lm0128i03
replace read_german0 = lb1233 if read_german0 < 0 | read_german0 >= .
recode speak_german0 (1=4) (2=3) (3=2) (4=1) (5=0) (-10/-1 = .)
lab val speak_german0 language
recode write_german0 (1=4) (2=3) (3=2) (4=1) (5=0) (-10/-1 = .)
lab val write_german0 language
recode read_german0 (1=4) (2=3) (3=2) (4=1) (5=0) (-10/-1 = .)
lab val read_german0 language
gen german0_additive = speak_german0 + read_german0 + write_german0
lab var german0_additive "pre-migration german profficiency"
bysort pid (syear): carryforward german0_additive, replace
bysort pid (minusyear): carryforward german0_additive, replace

gen stay_duryr = intyear - arrival_yr
replace stay_duryr = . if stay_duryr < 0
lab var stay_duryr "duration of stay in years"
gen stay_durm = intdate - arrival_date
lab var stay_durm "duration of stay in months"
summarize stay_duryr stay_durm

gen arriv_fam = lr3133 == 1
recode arriv_fam (. = 0) if lr3132 == 1
recode arriv_fam (. = 0) if lr3134 == 1
recode arriv_fam (. = 0) if lr3135 == 1
bysort pid (syear): carryforward arriv_fam, replace
bysort pid (minusyear): carryforward arriv_fam, replace
lab var arriv_fam "arrived with family"

recode lb1246 lb1247_v1 lb1247_v2 lb1247_v3 lb1247_v4 lb1248 ///
    (-10/-1 = .)
bysort pid (syear): carryforward lb1246 lb1247_v1 lb1247_v2 ///
    lb1247_v3 lb1247_v4 lb1248, replace
bysort pid (minusyear): carryforward lb1246 lb1247_v1 lb1247_v2 ///
    lb1247_v3 lb1247_v4 lb1248, replace

gen support0 = 1 if lb1246 == 1 | lb1247_v1 == 1 | ///
    lb1247_v2 == 1 | lb1247_v3 == 1 | lb1247_v4 == 1
recode support0 .= 0 if lb1248 == 1
lab var support0 "family/friends in Germany before arrival"
gen friends0 = 1 if lb1247_v1 == 1 | lb1247_v2 == 1 | ///
    lb1247_v3 == 1 | lb1247_v4 == 1
recode friends0 .= 0 if support0 == 1
recode friends0 .= 0 if lb1248 == 1
lab var friends0 "pre-migration friends in Germany"
gen family0 = 1 if lb1246 == 1
recode family0 .= 0 if support0 == 1
recode family0 .= 0 if lb1247_v1 == 1 | lb1247_v2 == 1 | ///
    lb1247_v3 == 1 | lb1247_v4 == 1
recode family0 .= 0 if lb1248 == 1
lab var family0 "pre-migration family in Germany"

clonevar hwunt = hlj0005_h
label def hwunt 1 "shared accommodation" ///
    2 "private accommodation" 3 "other", replace
gen priv_accom = hwunt == 2 if hwunt < .
lab var priv_accom "private accommodation (house/flat)"

mvdecode ple0008, mv(-1,-2,-3,-5,-6,-7,-9)
gen healthy = 6 - ple0008
lab def healthy 1 "very bad" 5 "very good"
lab val healthy healthy
lab var healthy "self-rated health"

mvdecode lr3048, mv(-1,-2,-3,-5,-6,-7,-9)
gen health0 = lr3048
lab var health0 "premigration health satisfacation"

mvdecode lr3122 lr3123 lr3124 lr3125 lr3126 lr3127 lr3128, ///
    mv(-1,-2,-3,-5,-6,-7,-9)
gen trauma_exp = 0 if lr3129 == 1
replace trauma_exp = 1 if lr3122 == 1 | lr3123 == 1 | ///
    lr3124 == 1 | lr3125 == 1 | lr3126 == 1 | lr3127 == 1 | ///
    lr3128 == 1
lab var trauma_exp "traumatic experience"
bysort pid (syear): carryforward trauma_exp, replace
bysort pid (minusyear): carryforward trauma_exp, replace
tabulate trauma_exp, m

count
summarize total_years_edu0 work0 german0_additive priv_accom
summarize healthy health0 trauma_exp support0
describe, short
save $mydata/msuemer/clean_confounders, replace
display "13C3 ok"
