*==============================================================================*
* clean_citizenship.do
*
* GENERATED BY src/python/lmi/remote/make_partc_jobs.py
*           -- DO NOT EDIT BY HAND, REGENERATE
*
* Purpose : SOEP country codes -> ISO 3166 numeric, keyed on the numeric
*           code rather than German label text.
* Source  : 00013_data_clean.do:793-905
* Runs    : SOEPremote (soep-exec@diw.de)
* Depends : clean_county
* Saves   : $mydata/msuemer/clean_citizenship
* Deviates: see the notes below
* Author  : Emre Suemer
*==============================================================================*
* ========================================================================
* PORT OF 00013_data_clean.do, PART C1 (orig lines 793-905)
* DOCUMENTATION, DO NOT SEND THIS PART
* ========================================================================
* Reads  $mydata/msuemer/clean_county
* Writes $mydata/msuemer/clean_citizenship
*
* Do not send until the previous job's listing shows its .dta saved.
* A missing input does not halt a SOEPremote job.
*
* The country block (orig :854-871). The authors' 1,184-line sub-do-file
* is called with `qui: do`, which is banned, and it matches on decoded
* German label TEXT -- unusable here, because label text differs between
* editions and any non-ASCII character is fatal to a job.
* 
* So the chain country_name_str -> citizenship_var -> iso3166 ->
* iso_num_o was executed in Python and collapsed to its composition:
* 65 direct code -> ISO-numeric assignments. Matching on the
* numeric code is immune to label text and is pure ASCII.
* 
* iso3166 is not built. The original renames it to citizenship_iso and
* drops it unused at :915, so nothing observes its absence.
* 
* Codes deliberately left at 0 (the original leaves them too): -2, -1, 98, 149, 172, 999.
*   98  Staatenlos  -> handled by the `stateless` flag below
*   -1/-2           -> SOEP missing codes
*   999/149/172     -> Ethnische Minderheiten / Kurdistan / Kaukasus,
*                      which are not countries
* 
* > CHECK `tab country_name if iso_num_o == 0` IN THE LISTING. It must
* > show only those six codes. Anything else is a citizenship this
* > mapping missed, and the run has to be redone with it added.
* 
* stateless: the original sets it from the English name string
* (citizenship == "stateless"). Code 98 is the only pgnation value that
* reaches that string, so it is set from the code directly and the
* English-name variable is never built.
* ========================================================================

* ============ SEND FROM HERE DOWN (below your auth header) ============
use $mydata/msuemer/clean_county, clear
count
xtset pid syear

gen year = syear
assert year != 2015

gen female = sex == 2
lab var female "female"
tabulate female

gen h_child = d11107 >= 1 if d11107 < .
label var h_child "children in the household"

rename partner partner_orig
tabulate partner_orig pgfamstd, m
gen partner = .
label var partner "partner in the household"
replace partner = 1 if inlist(plj0627,1)
replace partner = 1 if inlist(plj0630,1)
replace partner = 1 if inlist(partner_orig,1,2)
recode partner .= 0 if inlist(plj0627,2,3,4,5)
recode partner .= 0 if inlist(plj0630,2,3,4,5)
recode partner .= 0 if inlist(partner_orig,0)
recode partner .= 0 if inlist(plj0629,2)
tabulate partner, m

gen age = syear - gebjahr if gebjahr > 0
lab var age "current age"
bysort pid (syear): egen age1st = min(age)
lab var age1st "age the first interview"
gen age_arriv = arrival_yr - gebjahr if gebjahr > 0
lab var age_arriv "age at arrival"
summarize age age1st age_arriv

clonevar country_name = pgnation
gen iso_num_o = 0
replace iso_num_o = 276 if country_name == 1
replace iso_num_o = 792 if country_name == 2
replace iso_num_o = 642 if country_name == 21
replace iso_num_o = 364 if country_name == 24
replace iso_num_o = 100 if country_name == 29
replace iso_num_o = 760 if country_name == 30
replace iso_num_o = 643 if country_name == 32
replace iso_num_o = 356 if country_name == 42
replace iso_num_o = 4 if country_name == 43
replace iso_num_o = 682 if country_name == 46
replace iso_num_o = 231 if country_name == 47
replace iso_num_o = 288 if country_name == 49
replace iso_num_o = 50 if country_name == 50
replace iso_num_o = 788 if country_name == 52
replace iso_num_o = 566 if country_name == 54
replace iso_num_o = 368 if country_name == 60
replace iso_num_o = 144 if country_name == 65
replace iso_num_o = 524 if country_name == 66
replace iso_num_o = 504 if country_name == 67
replace iso_num_o = 498 if country_name == 73
replace iso_num_o = 8 if country_name == 75
replace iso_num_o = 422 if country_name == 76
replace iso_num_o = 417 if country_name == 77
replace iso_num_o = 804 if country_name == 78
replace iso_num_o = 12 if country_name == 79
replace iso_num_o = 818 if country_name == 81
replace iso_num_o = 762 if country_name == 82
replace iso_num_o = 706 if country_name == 84
replace iso_num_o = 586 if country_name == 85
replace iso_num_o = 232 if country_name == 89
replace iso_num_o = 400 if country_name == 90
replace iso_num_o = 854 if country_name == 94
replace iso_num_o = 860 if country_name == 97
replace iso_num_o = 24 if country_name == 102
replace iso_num_o = 404 if country_name == 110
replace iso_num_o = 434 if country_name == 111
replace iso_num_o = 70 if country_name == 120
replace iso_num_o = 807 if country_name == 121
replace iso_num_o = 324 if country_name == 125
replace iso_num_o = 384 if country_name == 127
replace iso_num_o = 31 if country_name == 130
replace iso_num_o = 800 if country_name == 135
replace iso_num_o = 466 if country_name == 138
replace iso_num_o = 120 if country_name == 139
replace iso_num_o = 999 if country_name == 140
replace iso_num_o = 268 if country_name == 141
replace iso_num_o = 729 if country_name == 142
replace iso_num_o = 178 if country_name == 143
replace iso_num_o = 496 if country_name == 145
replace iso_num_o = 148 if country_name == 147
replace iso_num_o = 51 if country_name == 148
replace iso_num_o = 887 if country_name == 151
replace iso_num_o = 275 if country_name == 152
replace iso_num_o = 795 if country_name == 155
replace iso_num_o = 694 if country_name == 158
replace iso_num_o = 686 if country_name == 162
replace iso_num_o = 688 if country_name == 165
replace iso_num_o = 270 if country_name == 166
replace iso_num_o = 499 if country_name == 168
replace iso_num_o = 646 if country_name == 178
replace iso_num_o = 104 if country_name == 181
replace iso_num_o = 562 if country_name == 183
replace iso_num_o = 643 if country_name == 188
replace iso_num_o = 643 if country_name == 195
replace iso_num_o = 999 if country_name == 196

tabulate country_name if iso_num_o == 0, m
count if iso_num_o == 0

rename iso_num_o citizenship_iso_num
label var citizenship_iso_num "citizenship: iso code (numeric)"

gen stateless = 1 if country_name == 98
bysort pid (syear): carryforward stateless, replace
bysort pid (minusyear): carryforward stateless, replace
recode stateless (. = 0)
label var stateless "reported stateless"
tabulate stateless, m
soepdrop country_name

count
save $mydata/msuemer/clean_citizenship, replace
display "13C1 ok"
