*==============================================================================*
* clean_lingprox.do
*
* GENERATED BY src/python/lmi/remote/make_partc_jobs.py
*           -- DO NOT EDIT BY HAND, REGENERATE
*
* Purpose : Melitz & Toubal linguistic-proximity-to-German table, embedded
*           by input, restricted to the origins that occur.
* Source  : 00013_data_clean.do:984-1010
* Runs    : SOEPremote (soep-exec@diw.de)
* Depends : (nothing)
* Saves   : $mydata/msuemer/clean_lingprox
* Deviates: see the notes below
* Author  : Emre Suemer
*==============================================================================*
* ========================================================================
* PORT OF 00013_data_clean.do, LINGUISTIC PROXIMITY (orig lines 984-1010)
* DOCUMENTATION, DO NOT SEND THIS PART
* ========================================================================
* Reads  $mydata/msuemer/(nothing)
* Writes $mydata/msuemer/clean_lingprox
*
* Do not send until the previous job's listing shows its .dta saved.
* A missing input does not halt a SOEPremote job.
*
* The Melitz-Toubal linguistic-proximity table (orig :984-1010).
* 
* The original builds it inside a preserve block from two local .dta
* files (ling_web, proxling). Those cannot be attached to a job, so the
* merge was rebuilt locally and the result is embedded with `input`.
* 
* 60 rows: every ISO3 that occurs in this sample, plus ISR,
* which the original substitutes for PSE. Origins that never occur are
* omitted -- the original drops them anyway (`drop if _merge == 2`), so
* the merge result is identical.
* 
* Values are sent as integers scaled by 1,000,000 and divided back
* down, the same encoding the supply panel uses.
* 
* Melitz, J. & Toubal, F. (2014), Journal of International Economics
* 92(2), 351-363.
* ========================================================================

* ============ SEND FROM HERE DOWN (below your auth header) ============
clear
input str3 iso3_o double p1 double p2
"AFG" 250000 83144
"AGO" 250000 115728
"ALB" 250000 99886
"ARM" 250000 118099
"AZE" 0 87555
"BFA" 0 0
"BGD" 250000 165244
"BGR" 250000 138399
"BIH" 250000 135555
"CIV" 0 0
"CMR" 0 0
"COG" 0 0
"DZA" 0 68014
"EGY" 0 68014
"ERI" 0 69626
"ETH" 0 68298
"GEO" 0 18023
"GHA" 0 0
"GIN" 0 0
"GMB" 0 0
"IND" 0 0
"IRN" 180000 93087
"IRQ" 0 68014
"ISR" 32500 60386
"JOR" 0 68014
"KEN" 0 29786
"KGZ" 67500 83492
"LBN" 0 68014
"LBY" 0 68014
"LKA" 250000 87346
"MAR" 0 68014
"MDA" 250000 174161
"MKD" 250000 138399
"MLI" 0 0
"MMR" 0 70954
"MNE" 250000 147126
"MNG" 0 53975
"NER" 0 0
"NGA" 0 0
"NPL" 250000 145323
"PAK" 250000 103491
"ROU" 250000 174161
"RUS" 250000 129956
"RWA" 0 68393
"SAU" 0 68014
"SDN" 0 68014
"SEN" 0 42212
"SLE" 0 0
"SOM" 0 58053
"SRB" 250000 147126
"SYR" 0 68014
"TCD" 0 0
"TJK" 250000 95238
"TKM" 0 87555
"TUN" 0 68014
"TUR" 0 87555
"UGA" 0 0
"UKR" 250000 115547
"UZB" 40000 87885
"YEM" 0 68014
end
replace p1 = p1/1000000
replace p2 = p2/1000000
rename p1 proxling
rename p2 proxling2
isid iso3_o
count
summarize proxling proxling2
save $mydata/msuemer/clean_lingprox, replace
display "ling prox ok"
