*==============================================================================*
* clean_citizenship_tc.do
*
* GENERATED BY src/python/lmi/remote/make_partc_jobs.py
*           -- DO NOT EDIT BY HAND, REGENERATE
*
* Purpose : The time-constant citizenship variable, plus the inverse ISO
*           map the authors keep in 00_X_iso.do.
* Source  : 00013_data_clean.do:917-985
* Runs    : SOEPremote (soep-exec@diw.de)
* Depends : clean_citizenship
* Saves   : $mydata/msuemer/clean_citizenship_tc
* Deviates: see the notes below
* Author  : Emre Suemer
*==============================================================================*
* ========================================================================
* PORT OF 00013_data_clean.do, PART C2 (orig lines 917-985)
* DOCUMENTATION, DO NOT SEND THIS PART
* ========================================================================
* Reads  $mydata/msuemer/clean_citizenship
* Writes $mydata/msuemer/clean_citizenship_tc
*
* Do not send until the previous job's listing shows its .dta saved.
* A missing input does not halt a SOEPremote job.
*
* The time-constant citizenship construction (orig :917-991), unchanged,
* plus the inverse map that the authors keep in 00_X_iso.do -- another
* `qui: do`, 250 lines. Only the 62 codes that occur are
* emitted; the rest could never match.
* 
* KOS is not special-cased here. The original adds
* `replace cou_help = "KOS" if citizenship_iso_num_tc == 999` after the
* sub-do-file because 999 is its own invention (Kosovo has no ISO number);
* 999 is already in the generated list below, so the extra line would be a
* no-op and is omitted.
* ========================================================================

* ============ SEND FROM HERE DOWN (below your auth header) ============
use $mydata/msuemer/clean_citizenship, clear
count
xtset pid syear

recode citizenship_iso_num (0 = .)
gen helpvar = citizenship_iso_num if n == 1
bysort pid (syear): carryforward helpvar, replace
replace helpvar = citizenship_iso_num if helpvar >= .
replace helpvar = citizenship_iso_num if helpvar >= . & n == 2
bysort pid (syear): carryforward helpvar, replace
bysort pid (minusyear): carryforward helpvar, replace
replace helpvar = citizenship_iso_num if helpvar >= . & n == 3
bysort pid (syear): carryforward helpvar, replace
bysort pid (minusyear): carryforward helpvar, replace
replace helpvar = citizenship_iso_num if helpvar >= . & n == 4
bysort pid (syear): carryforward helpvar, replace
bysort pid (minusyear): carryforward helpvar, replace

rename helpvar citizenship_iso_num_tc
recode citizenship_iso_num_tc (. = 0)
label variable citizenship_iso_num_tc "1st reported citizenship, num"
soepdrop citizenship_iso_num

gen cou_help = ""
replace cou_help = "DEU" if citizenship_iso_num_tc == 276
replace cou_help = "TUR" if citizenship_iso_num_tc == 792
replace cou_help = "ROU" if citizenship_iso_num_tc == 642
replace cou_help = "IRN" if citizenship_iso_num_tc == 364
replace cou_help = "BGR" if citizenship_iso_num_tc == 100
replace cou_help = "SYR" if citizenship_iso_num_tc == 760
replace cou_help = "RUS" if citizenship_iso_num_tc == 643
replace cou_help = "IND" if citizenship_iso_num_tc == 356
replace cou_help = "AFG" if citizenship_iso_num_tc == 4
replace cou_help = "SAU" if citizenship_iso_num_tc == 682
replace cou_help = "ETH" if citizenship_iso_num_tc == 231
replace cou_help = "GHA" if citizenship_iso_num_tc == 288
replace cou_help = "BGD" if citizenship_iso_num_tc == 50
replace cou_help = "TUN" if citizenship_iso_num_tc == 788
replace cou_help = "NGA" if citizenship_iso_num_tc == 566
replace cou_help = "IRQ" if citizenship_iso_num_tc == 368
replace cou_help = "LKA" if citizenship_iso_num_tc == 144
replace cou_help = "NPL" if citizenship_iso_num_tc == 524
replace cou_help = "MAR" if citizenship_iso_num_tc == 504
replace cou_help = "MDA" if citizenship_iso_num_tc == 498
replace cou_help = "ALB" if citizenship_iso_num_tc == 8
replace cou_help = "LBN" if citizenship_iso_num_tc == 422
replace cou_help = "KGZ" if citizenship_iso_num_tc == 417
replace cou_help = "UKR" if citizenship_iso_num_tc == 804
replace cou_help = "DZA" if citizenship_iso_num_tc == 12
replace cou_help = "EGY" if citizenship_iso_num_tc == 818
replace cou_help = "TJK" if citizenship_iso_num_tc == 762
replace cou_help = "SOM" if citizenship_iso_num_tc == 706
replace cou_help = "PAK" if citizenship_iso_num_tc == 586
replace cou_help = "ERI" if citizenship_iso_num_tc == 232
replace cou_help = "JOR" if citizenship_iso_num_tc == 400
replace cou_help = "BFA" if citizenship_iso_num_tc == 854
replace cou_help = "UZB" if citizenship_iso_num_tc == 860
replace cou_help = "AGO" if citizenship_iso_num_tc == 24
replace cou_help = "KEN" if citizenship_iso_num_tc == 404
replace cou_help = "LBY" if citizenship_iso_num_tc == 434
replace cou_help = "BIH" if citizenship_iso_num_tc == 70
replace cou_help = "MKD" if citizenship_iso_num_tc == 807
replace cou_help = "GIN" if citizenship_iso_num_tc == 324
replace cou_help = "CIV" if citizenship_iso_num_tc == 384
replace cou_help = "AZE" if citizenship_iso_num_tc == 31
replace cou_help = "UGA" if citizenship_iso_num_tc == 800
replace cou_help = "MLI" if citizenship_iso_num_tc == 466
replace cou_help = "CMR" if citizenship_iso_num_tc == 120
replace cou_help = "KOS" if citizenship_iso_num_tc == 999
replace cou_help = "GEO" if citizenship_iso_num_tc == 268
replace cou_help = "SDN" if citizenship_iso_num_tc == 729
replace cou_help = "COG" if citizenship_iso_num_tc == 178
replace cou_help = "MNG" if citizenship_iso_num_tc == 496
replace cou_help = "TCD" if citizenship_iso_num_tc == 148
replace cou_help = "ARM" if citizenship_iso_num_tc == 51
replace cou_help = "YEM" if citizenship_iso_num_tc == 887
replace cou_help = "PSE" if citizenship_iso_num_tc == 275
replace cou_help = "TKM" if citizenship_iso_num_tc == 795
replace cou_help = "SLE" if citizenship_iso_num_tc == 694
replace cou_help = "SEN" if citizenship_iso_num_tc == 686
replace cou_help = "SRB" if citizenship_iso_num_tc == 688
replace cou_help = "GMB" if citizenship_iso_num_tc == 270
replace cou_help = "MNE" if citizenship_iso_num_tc == 499
replace cou_help = "RWA" if citizenship_iso_num_tc == 646
replace cou_help = "MMR" if citizenship_iso_num_tc == 104
replace cou_help = "NER" if citizenship_iso_num_tc == 562
rename cou_help citizenship_iso_tc
replace citizenship_iso_tc = "missing" if citizenship_iso_tc == ""
label variable citizenship_iso_tc "1st reported citizenship, iso"
tabulate citizenship_iso_tc, m

label define immigroup 1 "SYR" 2 "AFG" 3 "IRQ" 4 "Eritrea" ///
    5 "IRN" 6 "rest MENA" 7 "former USSR" 8 "West Balkan" ///
    9 "Rest Africa" 10 "Rest" 11 "stateless", replace

gen immigroup_nat = .
replace immigroup_nat = 1 if inlist(citizenship_iso_tc,"SYR")
replace immigroup_nat = 2 if inlist(citizenship_iso_tc,"AFG")
replace immigroup_nat = 3 if inlist(citizenship_iso_tc,"IRQ")
replace immigroup_nat = 4 if inlist(citizenship_iso_tc,"ERI")
replace immigroup_nat = 5 if inlist(citizenship_iso_tc,"IRN")
replace immigroup_nat = 6 if ///
    inlist(citizenship_iso_tc,"DZA","LBN","MAR","PSE")
replace immigroup_nat = 6 if ///
    inlist(citizenship_iso_tc,"EGY","YEM","SAU","TUN","JOR") | ///
    inlist(citizenship_iso_tc,"LBY","ARE","KWT")
replace immigroup_nat = 7 if ///
    inlist(citizenship_iso_tc,"RUS","ARM","AZE","GEO","KGZ")
replace immigroup_nat = 7 if ///
    inlist(citizenship_iso_tc,"MDA","TJK","TKM","UKR","UZB") | ///
    inlist(citizenship_iso_tc,"MNG")
replace immigroup_nat = 8 if ///
    inlist(citizenship_iso_tc,"ALB","BIH","KOS","MKD","MNE") | ///
    inlist(citizenship_iso_tc,"SRB","HRV")
replace immigroup_nat = 9 if ///
    inlist(citizenship_iso_tc,"BFA","CIV","CMR","COG","ETH") | ///
    inlist(citizenship_iso_tc,"GHA","GIN","GMB","KEN")
replace immigroup_nat = 9 if ///
    inlist(citizenship_iso_tc,"MLI","NER","NGA","RWA","SDN") | ///
    inlist(citizenship_iso_tc,"SEN","SLE","SOM")
replace immigroup_nat = 9 if ///
    inlist(citizenship_iso_tc,"TCD","UGA","AGO","GNB","ROU")
replace immigroup_nat = 10 if ///
    inlist(citizenship_iso_tc,"BGD","NPL","IND","LKA","PAK") | ///
    inlist(citizenship_iso_tc,"TUR")
replace immigroup_nat = 10 if ///
    inlist(citizenship_iso_tc,"FRA","GBR","GRC","ITA","VEN")
recode immigroup_nat . = 11 if stateless == 1
label variable immigroup_nat "citizenship, aggr"
label values immigroup_nat immigroup
tabulate immigroup_nat, m

label define citiz_tc3 1 "Good remain perspectives" ///
    2 "Secure" 3 "Other", replace
gen citiz_tc3 = .
replace citiz_tc3 = 1 if ///
    inlist(citizenship_iso_tc,"SYR","IRQ","IRN","ERI","SOM")
replace citiz_tc3 = 2 if ///
    inlist(citizenship_iso_tc,"ALB","BIH","KOS","MKD","MNE") | ///
    inlist(citizenship_iso_tc,"SRB","GHA","SEN")
recode citiz_tc3 . = 3 if immigroup_nat < .
label variable citiz_tc3 "coo, clustering"
label values citiz_tc3 citiz_tc3
tabulate citiz_tc3, m

count
save $mydata/msuemer/clean_citizenship_tc, replace
display "13C2 ok"
