*==============================================================================*
* fig02_certificate.do                      (was 00023E3_analyses_remote.do)
*
* GENERATED BY src/analyses/remote/tools/make_23_jobs.py
*           -- DO NOT EDIT BY HAND, REGENERATE
*
* Purpose : Paper FIGURE 2, PANEL C. Average marginal effect of county
*           course supply on Pr(obtainment of a language certificate),
*           evaluated at eight durations of stay: 0, 6, 12, 18, 24, 30, 36
*           and 42 months (stay_dur is in months/12, so 0 to 3.5 in steps of
*           0.5). This is Model 4.2 of paper Table 4 read as a slope over
*           duration -- the paper's point being that the effect is positive
*           in the first months and then fades out. The plotted numbers are
*           also tabulated in the supplement as Table S12.
* Source  : 00023_mult_analyses.do:991-1023 (the mimrgns + marginsplot block)
* Runs    : SOEPremote (soep-exec@diw.de)
* Depends : impute_sample.do -> $mydata/msuemer/sample_imputed
* Saves   : $mydata/msuemer/fig02_cert  (mi estimation results, write-only)
* Result  : results/comparisons/fig02_marginal_effects.md
*           results/figures/fig02_panel_c.{png,svg}, drawn locally by
*           src/python/lmi/figures/fig02_marginal_effects.py
* Deviates: see FORCED DEVIATIONS below
* Author  : Emre Suemer, 2026-08-14
*==============================================================================*
* DOCUMENTATION, DO NOT SEND THIS PART
*
* ---------------- THREE NAMES, DELIBERATELY DISTINCT ----------------
*   m_0042p  the authors' own estimates, written by their Table 4 block
*   m_0042e  the in-memory esample marker this job creates (port's name)
*   fig02_cert  the .ster file this job writes on the server (migration's name)
* Only the last one changed in the migration, which is what holds the send
* block's diff against the pre-migration version to two $mydata/ lines.
*
* ---------------- WHY THIS RE-ESTIMATES THE MODEL ----------------
* The authors call `mimrgns using $output/m_0042p, esample(m_0042p)`,
* reusing the estimates their Table 4 block left behind. Both halves of that
* need state the Table 4 job cannot hand over: `using` reads the .ster file,
* which DOES persist in $mydata, but `esample()` names a VARIABLE that
* `mi estimate` creates IN MEMORY to mark the estimation sample -- and memory
* does not survive between SOEPremote jobs. Re-running the regression here
* recreates both, and the estimation is deterministic (the imputations are
* already fixed in sample_imputed), so the coefficients printed below must
* equal tab04_intermediate_outcomes.do's Model 4.2 column exactly. That
* equality is a free correctness check, not a duplicated result.
*
* ---------------- NOTHING STALE CAN REACH IT ----------------
* Reads sample_imputed, written 2026-08-13 by impute_sample (job 244564) on
* the cold rebuild. Writes fig02_cert -- a name that has never existed on the
* server. The pre-migration job saved to m_0042e instead, and that copy may
* still be there; it is now unreachable from this job. SOEPremote does not
* halt on runtime errors, so a job re-run into an existing name that fails
* partway leaves the OLD file sitting there looking healthy; writing to a
* fresh name makes that failure loud.
*
* ---------------- WHY THREE JOBS AND NOT ONE ----------------
* The three panels are independent, so splitting costs nothing: send all
* three together and wait once. A single job would run three imputed
* regressions plus three 20-imputation margins sweeps, and if it timed out or
* arrived truncated it would not say which panel was at fault.
*
* ---------------- FORCED DEVIATIONS ----------------
* (1) `marginsplot` and its four `graph save`/`graph export` lines REMOVED.
*     No image can come back from SOEPremote. The job returns the margins
*     TABLE instead -- eight rows of dy/dx, SE, t, p and 95% CI -- which is
*     everything the plot is drawn from. The panel is drawn locally by
*     src/python/lmi/figures/fig02_marginal_effects.py.
* (2) `eststo` and `_mi_addstats` dropped: this job builds no table, so it
*     needs neither stored estimates nor the added r2/groups scalars. The
*     preamble is still tab03_employment.do's verbatim, `_mi_addstats`
*     included but never called, so the control set cannot drift from the one
*     that reproduced Table 3.
* (3) #delimit -> `///`, as in every other ported job.
* (4) `expression(100*(predict(xb)))` REMOVED, and the x100 done locally
*     instead. THE ONLY DEVIATION IN THESE JOBS THAT TOUCHES THE STATA CODE,
*     so the reasoning is set out in full below under RESCALING.
* (5) `saving($output/m_0042p)` -> `saving($mydata/msuemer/fig02_cert)`; see
*     NOTHING STALE CAN REACH IT above.
*
* ---------------- RESCALING: WHY expression() IS GONE ----------------
* The authors write `expression(100*(predict(xb)))` here to report this panel
* in percentage points. That option is dropped and the x100 applied locally by
* src/python/lmi/figures/fig02_marginal_effects.py instead.
*
* IT IS EXACTLY EQUIVALENT, because the estimator is `reg`. The response is
* then linear in the parameters, so the marginal effect at a given stay_dur is
* just b_supply + stay_dur * b_interaction -- a linear combination -- and
* multiplying the response by 100 multiplies that combination, and its
* delta-method standard error, by exactly 100. t and p are unchanged and the
* confidence bounds scale with the estimate. Nothing is approximated.
* Confirmed empirically on Panel A, which has no expression(): its returned
* marginal effect at stay_dur = 0 is 0.232, exactly its own Model 2.2
* coefficient 0.2325.
*
* WHY IT WAS DROPPED. Panels B and C were sent twice on 2026-08-14 and neither
* produced any reply -- not a listing, not a bounce -- while Panel A and the
* Table 5 job, sent the same evening, both returned within the hour. The one
* token that distinguishes them from every job that has ever run on this
* account is `predict`, which appears in the send block of these two jobs and
* of no other. `predict` is the canonical way to generate individual-level
* fitted values, which is exactly what SOEPremote's confidentiality screening
* exists to catch, and a job held for manual review returns nothing until a
* person looks at it. Removing the option removes the token.
*
* It also removes a real cost: with expression(), margins must differentiate
* NUMERICALLY with respect to every model parameter (about 50 here, once per
* at() point, per imputation) rather than reading the derivative off the
* coefficient vector. That is the other candidate explanation for silence.
*
* WHAT THIS PANEL MUST RETURN, derived from the Table 4 run:
*     effect(stay_dur) = 100 * (0.0465 + stay_dur * -0.0236)
* i.e. at 0, 6 ... 42 months: 4.65 3.47 2.29 1.11 -0.07 -1.25 -2.43 -3.61
* Only the standard errors genuinely require this job -- they need the
* covariance between the two coefficients, which we do not hold locally.
*
* ---------------- SHARED WITH TABLE 3'S JOB ----------------
* The preamble ($controls_fv, $keeporder_controls, $coeflabels, $table_opt,
* _mi_addstats) is copied verbatim from tab03_employment.do, which reproduced
* paper Table 3 bit-identically on the 2026-08-13 cold run. Globals and
* programs do not survive between SOEPremote jobs, so every job carries its
* own copy; the generator copies it rather than restating it so the control
* set cannot drift between exhibits.
*
* ---------------- THE AUTHORS' PLOT SETTINGS, FOR THE LOCAL REDRAW ----------
*   y axis   ysc(r(-6.5 6.5)) ylabel(-6 (2) 6)
*   x axis   0 "0" 0.5 "6" 1 "12" 1.5 "18" 2 "24" 2.5 "30" 3 "36" 3.5 "42"
*            xtitle "Duration of stay (in months)", xsc(r(0.4 3.6))
*   ytitle   "Obtainment of a language certificate (pr)"
*   title    "Panel C. Pr(obtainment of a language certificate) / in percentage points, Model 4.2"
*   CI as a shaded area (recastci(rarea)), reference line at y = 0.
* Reproduced in the Python module named above, with ONE deliberate departure:
* the authors' ysc() range clips the confidence band at short durations, so the
* module widens it to fit and extends their tick sequence by its own step. The
* published figure clips too, but a band running off the top of the axis reads
* as a rendering fault rather than as a wide interval.
*
* ---------------- WHAT TO CHECK ----------------
*   the coefficient table -> must match the Model 4.2 column of
*        results/comparisons/tab04_intermediate_outcomes.md exactly.
*   the margins table -> about +4 to +5 p.p. below 6 months,
*        non-significant past 12 months.
*   8 rows in the margins table, N 5467 in the model.
*   `display "23E3 ok"` at the end -- with no dataset saved by this job,
*        that line and the margins table ARE the completion signal.
*
* > 1 imputed regression + a 20-imputation margins sweep. Slow; SOEPremote
* > may take longer than the usual hour to return this one.
*
* Pre-flight:
*   python3 src/analyses/remote/tools/preflight.py \\
*       src/stata/remote/fig02_certificate.do
*==============================================================================*

* ============ SEND FROM HERE DOWN (below your auth header) ============
use $mydata/msuemer/sample_imputed, clear
mi query
mi des, detail
mi convert flong, clear

global controls_fv ib1.immigroup_nat i.nuts1_first i.syear
global controls_fv $controls_fv i.msample i.work0
global controls_fv $controls_fv c.total_years_edu0
global controls_fv $controls_fv i.female i.h_child i.arriv_fam
global controls_fv $controls_fv i.family0 i.trauma_exp c.age1st
global controls_fv $controls_fv ib1.asyl_req_stat
global controls_fv $controls_fv c.z_foreign_share c.z_density
global controls_fv $controls_fv c.z_unemplrate c.z_consimmi c.z_cdu

global keeporder_controls total_years_edu0 1.work0 1.female
global keeporder_controls $keeporder_controls 1.h_child 1.arriv_fam
global keeporder_controls $keeporder_controls 1.family0 age1st
global keeporder_controls $keeporder_controls 1.trauma_exp
global keeporder_controls $keeporder_controls 2.asyl_req_stat
global keeporder_controls $keeporder_controls 3.asyl_req_stat
global keeporder_controls $keeporder_controls z_foreign_share
global keeporder_controls $keeporder_controls z_density
global keeporder_controls $keeporder_controls z_unemplrate
global keeporder_controls $keeporder_controls z_consimmi z_cdu

global coeflabels total_years_edu0 "Premigration years of education"
global coeflabels $coeflabels ///
    1.work0 "With premigration work experience"
global coeflabels $coeflabels 1.female "Female"
global coeflabels $coeflabels 1.h_child "Children below 16 in household"
global coeflabels $coeflabels ///
    1.arriv_fam "Arrival to Germany with family"
global coeflabels $coeflabels 1.family0 "Premigration family support"
global coeflabels $coeflabels age1st "Age at the first interview"
global coeflabels $coeflabels 1.trauma_exp "With trauma experiences"
global coeflabels $coeflabels 2.asyl_req_stat "-- Rejected"
global coeflabels $coeflabels 3.asyl_req_stat "-- No decision"
global coeflabels $coeflabels ///
    z_foreign_share "County share foreigners, std."
global coeflabels $coeflabels ///
    z_density "County population density, std."
global coeflabels $coeflabels ///
    z_unemplrate "County unemployment rate, std."
global coeflabels $coeflabels ///
    z_consimmi "County concerns immigration, std."
global coeflabels $coeflabels z_cdu "County share CDU/CSU voters, std."

global table_opt collabels(none) constant not wide
global table_opt $table_opt starlevels(+ 0.1 * 0.05 ** 0.01)
global table_opt $table_opt compress nogaps nodepvars
global table_opt $table_opt refcat(2.asyl_req_stat ///
    "Status of the asylum request (Ref.: approved): ", nolabel)
global table_opt $table_opt indicate("Survey year fe = *.syear" ///
    "Survey sample fe = *.msample" ///
    "Federal State fe = *.nuts1_first" ///
    "Country of origin (aggregated) fe = *.immigroup_nat")
global table_opt $table_opt scalars(N groups M_mi e_r2 e_r2a)
global table_opt $table_opt sfmt(%9.0f %9.0f %9.0f %9.4f %9.4f)

program define _mi_addstats
    quietly {
        capture soepdrop e_*
        args estimates
        est des `estimates'
        mi xeq: `r(cmdline)'; gen e_r2 = e(r2); gen e_r2a = e(r2_a)
        foreach var of varlist e_* {
            mi est, post: mean `var'
            local `var' = _b[`var']
            estadd scalar `var' = ``var'', replace: `estimates'
        }
        soepdrop e_*
        capture soepdrop groups
        bysort pid: generate groups = _n
        count if groups == 1
        local groups = r(N)
        display `groups'
        estadd scalar groups = `groups', replace: `estimates'
    }
end

capture soepdrop m_0042e
mi estimate, post dots ///
    saving($mydata/msuemer/fig02_cert, replace) esample(m_0042e): ///
    reg germ_cert_any $controls_fv ///
    c.stay_dur##c.z_ratio_courseoport ///
    [pweight=weight_p], vce(cluster pid)

mimrgns using $mydata/msuemer/fig02_cert, esample(m_0042e) ///
    dydx(z_ratio_courseoport) ///
    at(stay_dur=(0 0.5 (0.5) 3.5)) ///
    cmdmargins

display "23E3 ok"
