*==============================================================================*
* fig02_proficiency.do                      (was 00023E1_analyses_remote.do)
*
* GENERATED BY src/analyses/remote/tools/make_23_jobs.py
*           -- DO NOT EDIT BY HAND, REGENERATE
*
* Purpose : Paper FIGURE 2, PANEL A. Average marginal effect of county
*           course supply on German language proficiency,
*           evaluated at eight durations of stay: 0, 6, 12, 18, 24, 30, 36
*           and 42 months (stay_dur is in months/12, so 0 to 3.5 in steps of
*           0.5). This is Model 2.2 of paper Table 4 read as a slope over
*           duration -- the paper's point being that the effect is positive
*           in the first months and then fades out. The plotted numbers are
*           also tabulated in the supplement as Table S12.
* Source  : 00023_mult_analyses.do:927-955 (the mimrgns + marginsplot block)
* Runs    : SOEPremote (soep-exec@diw.de)
* Depends : impute_sample.do -> $mydata/msuemer/sample_imputed
* Saves   : $mydata/msuemer/fig02_germ  (mi estimation results, write-only)
* Result  : results/comparisons/fig02_marginal_effects.md
*           results/figures/fig02_panel_a.{png,svg}, drawn locally by
*           src/python/lmi/figures/fig02_marginal_effects.py
* Deviates: see FORCED DEVIATIONS below
* Author  : Emre Suemer, 2026-08-14
*==============================================================================*
* DOCUMENTATION, DO NOT SEND THIS PART
*
* ---------------- THREE NAMES, DELIBERATELY DISTINCT ----------------
*   m_0022p  the authors' own estimates, written by their Table 4 block
*   m_0022e  the in-memory esample marker this job creates (port's name)
*   fig02_germ  the .ster file this job writes on the server (migration's name)
* Only the last one changed in the migration, which is what holds the send
* block's diff against the pre-migration version to two $mydata/ lines.
*
* ---------------- WHY THIS RE-ESTIMATES THE MODEL ----------------
* The authors call `mimrgns using $output/m_0022p, esample(m_0022p)`,
* reusing the estimates their Table 4 block left behind. Both halves of that
* need state the Table 4 job cannot hand over: `using` reads the .ster file,
* which DOES persist in $mydata, but `esample()` names a VARIABLE that
* `mi estimate` creates IN MEMORY to mark the estimation sample -- and memory
* does not survive between SOEPremote jobs. Re-running the regression here
* recreates both, and the estimation is deterministic (the imputations are
* already fixed in sample_imputed), so the coefficients printed below must
* equal tab04_intermediate_outcomes.do's Model 2.2 column exactly. That
* equality is a free correctness check, not a duplicated result.
*
* ---------------- NOTHING STALE CAN REACH IT ----------------
* Reads sample_imputed, written 2026-08-13 by impute_sample (job 244564) on
* the cold rebuild. Writes fig02_germ -- a name that has never existed on the
* server. The pre-migration job saved to m_0022e instead, and that copy may
* still be there; it is now unreachable from this job. SOEPremote does not
* halt on runtime errors, so a job re-run into an existing name that fails
* partway leaves the OLD file sitting there looking healthy; writing to a
* fresh name makes that failure loud.
*
* ---------------- WHY THREE JOBS AND NOT ONE ----------------
* The three panels are independent, so splitting costs nothing: send all
* three together and wait once. A single job would run three imputed
* regressions plus three 20-imputation margins sweeps, and if it timed out or
* arrived truncated it would not say which panel was at fault.
*
* ---------------- FORCED DEVIATIONS ----------------
* (1) `marginsplot` and its four `graph save`/`graph export` lines REMOVED.
*     No image can come back from SOEPremote. The job returns the margins
*     TABLE instead -- eight rows of dy/dx, SE, t, p and 95% CI -- which is
*     everything the plot is drawn from. The panel is drawn locally by
*     src/python/lmi/figures/fig02_marginal_effects.py.
* (2) `eststo` and `_mi_addstats` dropped: this job builds no table, so it
*     needs neither stored estimates nor the added r2/groups scalars. The
*     preamble is still tab03_employment.do's verbatim, `_mi_addstats`
*     included but never called, so the control set cannot drift from the one
*     that reproduced Table 3.
* (3) #delimit -> `///`, as in every other ported job.
* (4) No `expression()` option in the original for this panel: proficiency
*     is an index, reported in scale points rather than percentage points.
*     Panels B and C are rescaled x100 locally; see their headers.
* (5) `saving($output/m_0022p)` -> `saving($mydata/msuemer/fig02_germ)`; see
*     NOTHING STALE CAN REACH IT above.
*
* ---------------- SHARED WITH TABLE 3'S JOB ----------------
* The preamble ($controls_fv, $keeporder_controls, $coeflabels, $table_opt,
* _mi_addstats) is copied verbatim from tab03_employment.do, which reproduced
* paper Table 3 bit-identically on the 2026-08-13 cold run. Globals and
* programs do not survive between SOEPremote jobs, so every job carries its
* own copy; the generator copies it rather than restating it so the control
* set cannot drift between exhibits.
*
* ---------------- THE AUTHORS' PLOT SETTINGS, FOR THE LOCAL REDRAW ----------
*   y axis   ysc(r(-0.25 0.45)) ylabel(-0.2(0.1)0.4)
*   x axis   0 "0" 0.5 "6" 1 "12" 1.5 "18" 2 "24" 2.5 "30" 3 "36" 3.5 "42"
*            xtitle "Duration of stay (in months)", xsc(r(0.4 3.6))
*   ytitle   "German language proficiency"
*   title    "Panel A. German language proficiency / Model 2.2"
*   CI as a shaded area (recastci(rarea)), reference line at y = 0.
* Reproduced in the Python module named above, with ONE deliberate departure:
* the authors' ysc() range clips the confidence band at short durations, so the
* module widens it to fit and extends their tick sequence by its own step. The
* published figure clips too, but a band running off the top of the axis reads
* as a rendering fault rather than as a wide interval.
*
* ---------------- WHAT TO CHECK ----------------
*   the coefficient table -> must match the Model 2.2 column of
*        results/comparisons/tab04_intermediate_outcomes.md exactly.
*   the margins table -> about +0.2 scale points at 0-6 months,
*        falling to non-significant past 12 months.
*   8 rows in the margins table, N 5467 in the model.
*   `display "23E1 ok"` at the end -- with no dataset saved by this job,
*        that line and the margins table ARE the completion signal.
*
* > 1 imputed regression + a 20-imputation margins sweep. Slow; SOEPremote
* > may take longer than the usual hour to return this one.
*
* Pre-flight:
*   python3 src/analyses/remote/tools/preflight.py \\
*       src/stata/remote/fig02_proficiency.do
*==============================================================================*

* ============ SEND FROM HERE DOWN (below your auth header) ============
use $mydata/msuemer/sample_imputed, clear
mi query
mi des, detail
mi convert flong, clear

global controls_fv ib1.immigroup_nat i.nuts1_first i.syear
global controls_fv $controls_fv i.msample i.work0
global controls_fv $controls_fv c.total_years_edu0
global controls_fv $controls_fv i.female i.h_child i.arriv_fam
global controls_fv $controls_fv i.family0 i.trauma_exp c.age1st
global controls_fv $controls_fv ib1.asyl_req_stat
global controls_fv $controls_fv c.z_foreign_share c.z_density
global controls_fv $controls_fv c.z_unemplrate c.z_consimmi c.z_cdu

global keeporder_controls total_years_edu0 1.work0 1.female
global keeporder_controls $keeporder_controls 1.h_child 1.arriv_fam
global keeporder_controls $keeporder_controls 1.family0 age1st
global keeporder_controls $keeporder_controls 1.trauma_exp
global keeporder_controls $keeporder_controls 2.asyl_req_stat
global keeporder_controls $keeporder_controls 3.asyl_req_stat
global keeporder_controls $keeporder_controls z_foreign_share
global keeporder_controls $keeporder_controls z_density
global keeporder_controls $keeporder_controls z_unemplrate
global keeporder_controls $keeporder_controls z_consimmi z_cdu

global coeflabels total_years_edu0 "Premigration years of education"
global coeflabels $coeflabels ///
    1.work0 "With premigration work experience"
global coeflabels $coeflabels 1.female "Female"
global coeflabels $coeflabels 1.h_child "Children below 16 in household"
global coeflabels $coeflabels ///
    1.arriv_fam "Arrival to Germany with family"
global coeflabels $coeflabels 1.family0 "Premigration family support"
global coeflabels $coeflabels age1st "Age at the first interview"
global coeflabels $coeflabels 1.trauma_exp "With trauma experiences"
global coeflabels $coeflabels 2.asyl_req_stat "-- Rejected"
global coeflabels $coeflabels 3.asyl_req_stat "-- No decision"
global coeflabels $coeflabels ///
    z_foreign_share "County share foreigners, std."
global coeflabels $coeflabels ///
    z_density "County population density, std."
global coeflabels $coeflabels ///
    z_unemplrate "County unemployment rate, std."
global coeflabels $coeflabels ///
    z_consimmi "County concerns immigration, std."
global coeflabels $coeflabels z_cdu "County share CDU/CSU voters, std."

global table_opt collabels(none) constant not wide
global table_opt $table_opt starlevels(+ 0.1 * 0.05 ** 0.01)
global table_opt $table_opt compress nogaps nodepvars
global table_opt $table_opt refcat(2.asyl_req_stat ///
    "Status of the asylum request (Ref.: approved): ", nolabel)
global table_opt $table_opt indicate("Survey year fe = *.syear" ///
    "Survey sample fe = *.msample" ///
    "Federal State fe = *.nuts1_first" ///
    "Country of origin (aggregated) fe = *.immigroup_nat")
global table_opt $table_opt scalars(N groups M_mi e_r2 e_r2a)
global table_opt $table_opt sfmt(%9.0f %9.0f %9.0f %9.4f %9.4f)

program define _mi_addstats
    quietly {
        capture soepdrop e_*
        args estimates
        est des `estimates'
        mi xeq: `r(cmdline)'; gen e_r2 = e(r2); gen e_r2a = e(r2_a)
        foreach var of varlist e_* {
            mi est, post: mean `var'
            local `var' = _b[`var']
            estadd scalar `var' = ``var'', replace: `estimates'
        }
        soepdrop e_*
        capture soepdrop groups
        bysort pid: generate groups = _n
        count if groups == 1
        local groups = r(N)
        display `groups'
        estadd scalar groups = `groups', replace: `estimates'
    }
end

capture soepdrop m_0022e
mi estimate, post dots ///
    saving($mydata/msuemer/fig02_germ, replace) esample(m_0022e): ///
    reg german_additive $controls_fv ///
    c.stay_dur##c.z_ratio_courseoport ///
    [pweight=weight_p], vce(cluster pid)

mimrgns using $mydata/msuemer/fig02_germ, esample(m_0022e) ///
    dydx(z_ratio_courseoport) ///
    at(stay_dur=(0 0.5 (0.5) 3.5)) ///
    cmdmargins

display "23E1 ok"
