*==============================================================================*
* tab04_intermediate_outcomes.do            (was 00023D_analyses_remote.do)
*
* GENERATED BY src/analyses/remote/tools/make_23_jobs.py
*           -- DO NOT EDIT BY HAND, REGENERATE
*
* Purpose : Mediation step 2 -- county course supply as the PREDICTOR of each
*           of the four intermediary outcomes in turn, without and with the
*           duration-of-stay interaction. Eight LPM/OLS models, one table.
*           Produces paper Table 4 and nothing else, hence the exhibit prefix.
* Source  : 00023_mult_analyses.do:748-927 (the do-file calls this "Table_4";
*           here the do-file's number and the paper's happen to agree -- the
*           block above it writes "Table_3" and the paper prints Table 5)
* Runs    : SOEPremote (soep-exec@diw.de)
* Depends : impute_sample.do -> $mydata/msuemer/sample_imputed
* Saves   : $mydata/msuemer/tab04_germ_m  tab04_germ_x   (proficiency)
*                           tab04_crs_m   tab04_crs_x    (course completion)
*                           tab04_cert_m  tab04_cert_x   (certificate)
*                           tab04_cont_m  tab04_cont_x   (contact)
*           (mi estimation results; write-only, see below)
* Result  : results/comparisons/tab04_intermediate_outcomes.md
* Deviates: see FORCED DEVIATIONS below
* Author  : Emre Suemer, 2026-08-14
*==============================================================================*
* DOCUMENTATION, DO NOT SEND THIS PART
*
* Mediation, step 2. Part C (paper Table 5) asks whether the intermediary
* outcomes carry the employment effect; this asks whether course supply moves
* the intermediaries at all, which is the other half of the same argument.
*   m_0021p/m_0022p  german_additive       DV: German language proficiency
*   m_0031p/m_0032p  int_course_finished   DV: integration course completed
*   m_0041p/m_0042p  germ_cert_any         DV: language certificate obtained
*   m_0051p/m_0052p  contacts_germ         DV: contact frequency with Germans
* The odd-numbered model of each pair is the main effect, the even-numbered
* one adds c.stay_dur##c.z_ratio_courseoport. The authors' reading, repeated
* for each pair: the main effect is not significant, but "the effect of
* LCSupply is positive and reduces over duration of stay" once the
* interaction is included.
*
* Note the DV of the fourth pair is `contacts_germ`, NOT the `time_germ` used
* as mediator 4 in Part C. That is the authors' own choice, kept as is.
*
* This esttab has NO transform(@*100 100): the four dependent variables sit
* on different scales, so coefficients print RAW at 4 d.p. The paper reports
* Panels A and D raw and Panels B and C multiplied by 100. Do not compare
* these magnitudes against Table 3's or Table 5's percentage points.
*
* ---------------- THE SAVED FILES ARE WRITE-ONLY ----------------
* Nothing in the port reads these eight .ster files back. The authors' own
* Part E calls `mimrgns using $output/m_0022p, esample(m_0022p)`, but
* esample() names a variable that `mi estimate` creates IN MEMORY, and memory
* does not cross SOEPremote jobs -- so E1-E3 re-estimate and save m_0022e,
* m_0032e, m_0042e instead. They are still saved because `mi estimate,
* saving()` is what makes any later mimrgns possible at all.
*
* They are saved under tab04_* rather than the authors' m_00NNp for the same
* reason tab03_employment writes tab03_total/tab03_interact: the 2026-08-08
* run left m_0021p..m_0052p on the server, built on the pre-rename chain.
* SOEPremote does not halt on runtime errors, so a job re-run into existing
* names that fails partway leaves the OLD file sitting there looking healthy.
* Writing to names that have never existed makes that failure loud.
*
* ---------------- WHY 00023 IS CHUNKED BY TABLE, NOT BY LINE ----------------
* `eststo` stores estimates in MEMORY, so a table's models and its `esttab`
* MUST travel in the same job. The chunking follows the eight `esttab` calls,
* not the 190-line budget:
*
*   A  201-343   m_001p m_002p                      -> paper Table 3
*   B  343-562   m_001p_i1..i13 (loop)              -> Table S6
*   C  562-753   m_0011p..m_0016p                   -> paper Table 5
*   D  753-927   m_0021p..m_0052p                   -> paper Table 4 (this)
*   E  927-1055  mimrgns x3                         -> Figures 2a-c
*   F  1055-1228 m_001r m_001c m_001f m_001l        -> Tables S8, S9
*   G  1228-1344 m_0061p m_0062p m_0071p m_0072p    -> Table S11
*   H  1344-1556 m_0017..m_0022                     -> Table S10
*
* ---------------- SHARED WITH TABLE 3'S JOB ----------------
* The preamble ($controls_fv, $keeporder_controls, $coeflabels, $table_opt,
* _mi_addstats) is copied verbatim from tab03_employment.do, which reproduced
* paper Table 3 to within Monte Carlo error and, on the 2026-08-13 cold run,
* bit-identically. Globals and programs do not survive between SOEPremote
* jobs, so every job carries its own copy; the generator copies it rather
* than restating it so the control set cannot drift between tables.
*
* ---------------- FORCED DEVIATIONS ----------------
* Inherited from tab03_employment.do, unchanged:
* (1) do config / cd / log using / exit / set matsize REMOVED. $controls_fv
*     is defined inside 00023 itself (orig :213), not in config.do.
* (2) #delimit -> the global-append form used throughout the port.
* (3) `capt program drop _mi_addstats` REMOVED (`drop` is banned; the program
*     is defined once per job). Inside it, `capture drop e_*` -> soepdrop.
* (4) esttab's `using "$output/Table_4", scsv replace` REMOVED -- no file can
*     come back from SOEPremote. The table prints to the listing and is
*     transcribed locally.
* (5) esttab's `keep(...)` REMOVED -- the OPTION NAME contains the banned
*     token `keep`. `order()` still fronts the variables of interest and
*     `indicate()` collapses the four fixed-effect blocks, so the control
*     rows simply print below. `nobaselevels` suppresses the spurious
*     `0.work0 ... 0.00 (.)` rows this creates and `varwidth(34)` stops the
*     five county labels truncating to an indistinguishable "Cou..".
* This job's own:
* (6) `saving($output/m_00NNp)` -> `saving($mydata/msuemer/tab04_*)`; see
*     THE SAVED FILES ARE WRITE-ONLY above. The eststo and esample() names
*     stay the authors' m_00NNp, so the esttab call is untouched.
*
* ---------------- READ THE ASYLUM LABELS SCEPTICALLY ----------------
* $coeflabels calls 2.asyl_req_stat "-- Rejected" and 3.asyl_req_stat
* "-- No decision", and $table_opt's refcat says the reference is "approved".
* ALL THREE ARE WRONG, and they are the authors' own: the model uses
* ib1.asyl_req_stat and 00013_data_clean.do:1541 defines 1 "no decision",
* 2 "approved", 3 "rejected". So the omitted reference is NO DECISION and the
* two printed rows are approved and rejected. Preserved verbatim so the port
* reproduces the authors' output; correct it in the write-up, not the code.
*
* ---------------- WHAT TO CHECK ----------------
*   mi query / mi des  -> M = 20, 5,467 obs before mi convert flong.
*   all eight `mi estimate` tables print in full, with dots for 20 imputes.
*   N 5467, groups 2730, M_mi 20 in every one of the eight columns.
*   the interaction c.stay_dur#c.z_ratio_courseoport in columns 2, 4, 6, 8
*        -> the authors' substantive result. Expect (2026-08-08 run):
*           -0.0870* / -1.41+ (as p.p., i.e. -0.0141) / -2.36** / -0.0084.
*   the main effect in columns 1, 3, 5, 7 -> expected non-significant:
*           0.0071 / 0.0068 / -0.0145 / -0.0191.
*   adjusted R2 -> 0.3900 0.3910 | 0.2014 0.2025 | 0.3380 0.3409 | 0.1492 0.1493
*   coefficients are RAW, not percentage points.
*
* > The 2026-08-13 cold rebuild reproduced Table 3 bit-identically against the
* > 2026-08-08 run, so a difference here now indicates a porting problem, not
* > Monte Carlo noise. Compare against the figures above before anything else.
*
* > 8 imputed regressions x 20 imputations with clustered SEs -- the slowest
* > job in the port so far. Check for a reply before resending.
*
* Pre-flight:
*   python3 src/analyses/remote/tools/preflight.py \
*       src/stata/remote/tab04_intermediate_outcomes.do
*==============================================================================*

* ============ SEND FROM HERE DOWN (below your auth header) ============
use $mydata/msuemer/sample_imputed, clear
mi query
mi des, detail
mi convert flong, clear

global controls_fv ib1.immigroup_nat i.nuts1_first i.syear
global controls_fv $controls_fv i.msample i.work0
global controls_fv $controls_fv c.total_years_edu0
global controls_fv $controls_fv i.female i.h_child i.arriv_fam
global controls_fv $controls_fv i.family0 i.trauma_exp c.age1st
global controls_fv $controls_fv ib1.asyl_req_stat
global controls_fv $controls_fv c.z_foreign_share c.z_density
global controls_fv $controls_fv c.z_unemplrate c.z_consimmi c.z_cdu

global keeporder_controls total_years_edu0 1.work0 1.female
global keeporder_controls $keeporder_controls 1.h_child 1.arriv_fam
global keeporder_controls $keeporder_controls 1.family0 age1st
global keeporder_controls $keeporder_controls 1.trauma_exp
global keeporder_controls $keeporder_controls 2.asyl_req_stat
global keeporder_controls $keeporder_controls 3.asyl_req_stat
global keeporder_controls $keeporder_controls z_foreign_share
global keeporder_controls $keeporder_controls z_density
global keeporder_controls $keeporder_controls z_unemplrate
global keeporder_controls $keeporder_controls z_consimmi z_cdu

global coeflabels total_years_edu0 "Premigration years of education"
global coeflabels $coeflabels ///
    1.work0 "With premigration work experience"
global coeflabels $coeflabels 1.female "Female"
global coeflabels $coeflabels 1.h_child "Children below 16 in household"
global coeflabels $coeflabels ///
    1.arriv_fam "Arrival to Germany with family"
global coeflabels $coeflabels 1.family0 "Premigration family support"
global coeflabels $coeflabels age1st "Age at the first interview"
global coeflabels $coeflabels 1.trauma_exp "With trauma experiences"
global coeflabels $coeflabels 2.asyl_req_stat "-- Rejected"
global coeflabels $coeflabels 3.asyl_req_stat "-- No decision"
global coeflabels $coeflabels ///
    z_foreign_share "County share foreigners, std."
global coeflabels $coeflabels ///
    z_density "County population density, std."
global coeflabels $coeflabels ///
    z_unemplrate "County unemployment rate, std."
global coeflabels $coeflabels ///
    z_consimmi "County concerns immigration, std."
global coeflabels $coeflabels z_cdu "County share CDU/CSU voters, std."

global table_opt collabels(none) constant not wide
global table_opt $table_opt starlevels(+ 0.1 * 0.05 ** 0.01)
global table_opt $table_opt compress nogaps nodepvars
global table_opt $table_opt refcat(2.asyl_req_stat ///
    "Status of the asylum request (Ref.: approved): ", nolabel)
global table_opt $table_opt indicate("Survey year fe = *.syear" ///
    "Survey sample fe = *.msample" ///
    "Federal State fe = *.nuts1_first" ///
    "Country of origin (aggregated) fe = *.immigroup_nat")
global table_opt $table_opt scalars(N groups M_mi e_r2 e_r2a)
global table_opt $table_opt sfmt(%9.0f %9.0f %9.0f %9.4f %9.4f)

program define _mi_addstats
    quietly {
        capture soepdrop e_*
        args estimates
        est des `estimates'
        mi xeq: `r(cmdline)'; gen e_r2 = e(r2); gen e_r2a = e(r2_a)
        foreach var of varlist e_* {
            mi est, post: mean `var'
            local `var' = _b[`var']
            estadd scalar `var' = ``var'', replace: `estimates'
        }
        soepdrop e_*
        capture soepdrop groups
        bysort pid: generate groups = _n
        count if groups == 1
        local groups = r(N)
        display `groups'
        estadd scalar groups = `groups', replace: `estimates'
    }
end

capture soepdrop m_0021p
eststo m_0021p: mi estimate, post dots ///
    saving($mydata/msuemer/tab04_germ_m, replace) esample(m_0021p): ///
    reg german_additive $controls_fv ///
    c.stay_dur c.z_ratio_courseoport ///
    [pweight=weight_p], vce(cluster pid)
_mi_addstats m_0021p
capture soepdrop m_0022p
eststo m_0022p: mi estimate, post dots ///
    saving($mydata/msuemer/tab04_germ_x, replace) esample(m_0022p): ///
    reg german_additive $controls_fv ///
    c.stay_dur##c.z_ratio_courseoport ///
    [pweight=weight_p], vce(cluster pid)
_mi_addstats m_0022p
capture soepdrop m_0031p
eststo m_0031p: mi estimate, post dots ///
    saving($mydata/msuemer/tab04_crs_m, replace) esample(m_0031p): ///
    reg int_course_finished $controls_fv ///
    c.stay_dur c.z_ratio_courseoport ///
    [pweight=weight_p], vce(cluster pid)
_mi_addstats m_0031p
capture soepdrop m_0032p
eststo m_0032p: mi estimate, post dots ///
    saving($mydata/msuemer/tab04_crs_x, replace) esample(m_0032p): ///
    reg int_course_finished $controls_fv ///
    c.stay_dur##c.z_ratio_courseoport ///
    [pweight=weight_p], vce(cluster pid)
_mi_addstats m_0032p
capture soepdrop m_0041p
eststo m_0041p: mi estimate, post dots ///
    saving($mydata/msuemer/tab04_cert_m, replace) esample(m_0041p): ///
    reg germ_cert_any $controls_fv ///
    c.stay_dur c.z_ratio_courseoport ///
    [pweight=weight_p], vce(cluster pid)
_mi_addstats m_0041p
capture soepdrop m_0042p
eststo m_0042p: mi estimate, post dots ///
    saving($mydata/msuemer/tab04_cert_x, replace) esample(m_0042p): ///
    reg germ_cert_any $controls_fv ///
    c.stay_dur##c.z_ratio_courseoport ///
    [pweight=weight_p], vce(cluster pid)
_mi_addstats m_0042p
capture soepdrop m_0051p
eststo m_0051p: mi estimate, post dots ///
    saving($mydata/msuemer/tab04_cont_m, replace) esample(m_0051p): ///
    reg contacts_germ $controls_fv ///
    c.stay_dur c.z_ratio_courseoport ///
    [pweight=weight_p], vce(cluster pid)
_mi_addstats m_0051p
capture soepdrop m_0052p
eststo m_0052p: mi estimate, post dots ///
    saving($mydata/msuemer/tab04_cont_x, replace) esample(m_0052p): ///
    reg contacts_germ $controls_fv ///
    c.stay_dur##c.z_ratio_courseoport ///
    [pweight=weight_p], vce(cluster pid)
_mi_addstats m_0052p
esttab m_0021p m_0022p m_0031p m_0032p ///
    m_0041p m_0042p m_0051p m_0052p, ///
    title("COURSE SUPPLY AND INTERMEDIARY OUTCOMES") ///
    order(z_ratio_courseoport stay_dur ///
        c.stay_dur#c.z_ratio_courseoport _cons) ///
    coeflabels(z_ratio_courseoport "County supply of courses, std." ///
        stay_dur "Duration of stay, in months (/12)" ///
        c.stay_dur#c.z_ratio_courseoport "x County supply" ///
        $coeflabels _cons "Constant") ///
    $table_opt nobaselevels varwidth(34) ///
    b(%9.4f) se(%9.4f) ///
    mtitles("German language proficiency" " " ///
        "Completion of an integration course" " " ///
        "Language certificate obtainment" " " ///
        "Contact frequency with Germans" " ")

display "23D ok"

