*==============================================================================*
* tab05_mediation.do                        (was 00023C_analyses_remote.do)
*
* GENERATED BY src/analyses/remote/tools/make_23_jobs.py
*           -- DO NOT EDIT BY HAND, REGENERATE
*
* Purpose : Mediation step 1 -- the DIRECT effect of county course supply on
*           employment, controlling for each intermediary outcome in turn and
*           then for all three jointly. Six LPMs, one table. Produces paper
*           Table 5 and nothing else, hence the exhibit prefix.
* Source  : 00023_mult_analyses.do:566-753
*           WARNING: the do-file writes this to "$output/Table_3". The paper
*           prints it as TABLE 5. The do-file's numbering is NOT the paper's
*           (its Table_2 is the paper's Table 3, its Table_4 is Table 4), and
*           this file is the sharpest instance -- see the mapping below.
* Runs    : SOEPremote (soep-exec@diw.de)
* Depends : impute_sample.do -> $mydata/msuemer/sample_imputed
* Saves   : $mydata/msuemer/tab05_germ      Model 1.3  + proficiency
*                           tab05_crs       Model 1.4  + course completion
*                           tab05_cert      Model 1.5  + certificate
*                           tab05_cont      Model 1.6  + contact
*                           tab05_all_crs   Model 1.7  all three, completion
*                           tab05_all_crt   Model 1.8  all three, certificate
*           (mi estimation results; write-only, nothing reads them back)
* Result  : results/comparisons/tab05_mediation.md
*           results/tables/tab05_mediation.tex, generated by
*           src/python/lmi/tables/tab05_mediation.py
* Deviates: see FORCED DEVIATIONS below
* Author  : Emre Suemer, 2026-08-14
*==============================================================================*
* DOCUMENTATION, DO NOT SEND THIS PART
*
* Mediation, step 1. Table 4's job asks whether course supply moves the
* intermediary outcomes; this asks whether the employment effect survives
* controlling for them, which is the other half of the same argument.
*   m_0011p  + German language proficiency               paper Model 1.3
*   m_0012p  + completion of an integration course       paper Model 1.4
*   m_0013p  + obtainment of a language certificate      paper Model 1.5
*   m_0014p  + contact frequency with Germans            paper Model 1.6
*   m_0015p  all three, using course completion          paper Model 1.7
*   m_0016p  all three, using the certificate instead    paper Model 1.8
*
* ---------------- READ THE MODEL NUMBERING TWICE ----------------
* Three numbering schemes are in play and none of them agree:
*   the authors' eststo names   m_0011p  m_0012p  m_0013p  m_0014p ...
*   the paper's model numbers   1.3      1.4      1.5      1.6     ...
*   this job's saved files      tab05_germ tab05_crs tab05_cert ...
* So m_0013p is the paper's Model 1.5, NOT its Model 1.3. Every write-up must
* go through the mapping above; the saved-file names are deliberately content
* names rather than numbers so they cannot be misread as either scheme.
*
* The authors' reading of the result: the total effect (2.97 in Table 3)
* barely moves and in most specifications RISES slightly, i.e. the mediators
* SUPPRESS rather than transmit it. Their note on Model 1.7: "1 SD in
* LCSupply increases employment probability by 3.2 percentage points" -- the
* estimate the paper's fiscal calculation rests on (0.0312 * 10,000 * 4,800
* euros = 1,497,600 euros of annual savings).
*
* Coefficients ARE in percentage points here: transform(@*100 100), as in
* Table 3's job. Unlike Table 4's, whose four DVs sit on different scales.
*
* ---------------- THE SAVED FILES ARE WRITE-ONLY ----------------
* Nothing in the port reads these six .ster files back. They are still saved
* because that is the authors' own shape, and because `mi estimate, saving()`
* is what would make any later `mimrgns` possible at all.
*
* They are saved under tab05_* rather than the authors' m_00NNp for the same
* reason tab04_intermediate_outcomes writes tab04_*: the 2026-08-08 run left
* m_0011p..m_0016p on the server, built on the PRE-RENAME chain. SOEPremote
* does not halt on runtime errors, so a job re-run into existing names that
* fails partway leaves the OLD file sitting there looking healthy. Writing to
* names that have never existed makes that failure loud.
*
* ---------------- SHARED WITH TABLE 3'S JOB ----------------
* The preamble ($controls_fv, $keeporder_controls, $coeflabels, $table_opt,
* _mi_addstats) is copied verbatim from tab03_employment.do, which reproduced
* paper Table 3 bit-identically on the 2026-08-13 cold run. Globals and
* programs do not survive between SOEPremote jobs, so every job carries its
* own copy; the generator copies it rather than restating it so the control
* set cannot drift between exhibits.
*
* ---------------- FORCED DEVIATIONS ----------------
* Inherited from tab03_employment.do, unchanged:
* (1) do config / cd / log using / exit / set matsize REMOVED. $controls_fv
*     is defined inside 00023 itself (orig :213), not in config.do.
* (2) #delimit -> the global-append form used throughout the port.
* (3) `capt program drop _mi_addstats` REMOVED (`drop` is banned; the program
*     is defined once per job). Inside it, `capture drop e_*` -> soepdrop.
* (4) esttab's `using "$output/Table_3", scsv replace` REMOVED -- no file can
*     come back from SOEPremote. The table prints to the listing and is
*     transcribed locally.
* (5) esttab's `keep(...)` REMOVED -- the OPTION NAME contains the banned
*     token `keep`. `order()` still fronts the variables of interest and
*     `indicate()` collapses the four fixed-effect blocks, so the control
*     rows simply print below. `nobaselevels` suppresses the spurious
*     `0.work0 ... 0.00 (.)` rows this creates and `varwidth(34)` stops the
*     county labels truncating to an indistinguishable "Cou..".
* This job's own:
* (6) `saving($output/m_00NNp)` -> `saving($mydata/msuemer/tab05_*)`; see THE
*     SAVED FILES ARE WRITE-ONLY above. The eststo and esample() names stay
*     the authors' m_00NNp, so the esttab call is untouched.
*
* ---------------- READ THE ASYLUM LABELS SCEPTICALLY ----------------
* $coeflabels calls 2.asyl_req_stat "-- Rejected" and 3.asyl_req_stat
* "-- No decision", and $table_opt's refcat says the reference is "approved".
* ALL THREE ARE WRONG, and they are the authors' own: the model uses
* ib1.asyl_req_stat and 00013_data_clean.do:1541 defines 1 "no decision",
* 2 "approved", 3 "rejected". So the omitted reference is NO DECISION and the
* two printed rows are approved and rejected. This is the third table the
* error reaches (Tables 2, 3 and 5) and the published Table 5 does not print
* these rows at all -- it says "Further individual and county-level controls
* are omitted". Preserved verbatim so the port reproduces the authors'
* output; correct it in the write-up, not the code.
*
* ---------------- WHAT TO CHECK ----------------
*   mi query / mi des  -> M = 20, 5,467 obs before mi convert flong.
*   all six `mi estimate` tables print in full, with dots for 20 imputes.
*   N 5467, groups 2730, M_mi 20 in every one of the six columns.
*   z_ratio_courseoport across all six columns -> near 3.0 p.p. and still
*        significant. Expect (2026-08-08 run, pre-migration chain):
*        2.97* 2.93* 3.04* 3.19** 3.13** 3.18** -- every one within 0.02
*        p.p. of the paper, with identical SEs and identical stars.
*   the mediators -> 1.64** 7.62** 4.02+ 5.06** separately; jointly
*        proficiency 0.51 goes non-significant while completion 6.73** and
*        contact 4.88** stay. That contrast IS the paper's argument.
*   adjusted R2 -> .2209 .2186 .2147 .2563 .2614 .2575, with Model 1.7 the
*        highest, which is the paper's "superior model fit" claim.
*
* > The 2026-08-13 cold rebuild reproduced Tables 3 and 4 bit-identically
* > against their 2026-08-08 runs, so a difference here now indicates a
* > porting problem, not Monte Carlo noise. Compare against the figures
* > above before anything else.
*
* > 6 imputed regressions x 20 imputations with clustered SEs. Slow; check
* > for a reply before resending.
*
* Pre-flight:
*   python3 src/analyses/remote/tools/preflight.py \\
*       src/stata/remote/tab05_mediation.do
*==============================================================================*

* ============ SEND FROM HERE DOWN (below your auth header) ============
use $mydata/msuemer/sample_imputed, clear
mi query
mi des, detail
mi convert flong, clear

global controls_fv ib1.immigroup_nat i.nuts1_first i.syear
global controls_fv $controls_fv i.msample i.work0
global controls_fv $controls_fv c.total_years_edu0
global controls_fv $controls_fv i.female i.h_child i.arriv_fam
global controls_fv $controls_fv i.family0 i.trauma_exp c.age1st
global controls_fv $controls_fv ib1.asyl_req_stat
global controls_fv $controls_fv c.z_foreign_share c.z_density
global controls_fv $controls_fv c.z_unemplrate c.z_consimmi c.z_cdu

global keeporder_controls total_years_edu0 1.work0 1.female
global keeporder_controls $keeporder_controls 1.h_child 1.arriv_fam
global keeporder_controls $keeporder_controls 1.family0 age1st
global keeporder_controls $keeporder_controls 1.trauma_exp
global keeporder_controls $keeporder_controls 2.asyl_req_stat
global keeporder_controls $keeporder_controls 3.asyl_req_stat
global keeporder_controls $keeporder_controls z_foreign_share
global keeporder_controls $keeporder_controls z_density
global keeporder_controls $keeporder_controls z_unemplrate
global keeporder_controls $keeporder_controls z_consimmi z_cdu

global coeflabels total_years_edu0 "Premigration years of education"
global coeflabels $coeflabels ///
    1.work0 "With premigration work experience"
global coeflabels $coeflabels 1.female "Female"
global coeflabels $coeflabels 1.h_child "Children below 16 in household"
global coeflabels $coeflabels ///
    1.arriv_fam "Arrival to Germany with family"
global coeflabels $coeflabels 1.family0 "Premigration family support"
global coeflabels $coeflabels age1st "Age at the first interview"
global coeflabels $coeflabels 1.trauma_exp "With trauma experiences"
global coeflabels $coeflabels 2.asyl_req_stat "-- Rejected"
global coeflabels $coeflabels 3.asyl_req_stat "-- No decision"
global coeflabels $coeflabels ///
    z_foreign_share "County share foreigners, std."
global coeflabels $coeflabels ///
    z_density "County population density, std."
global coeflabels $coeflabels ///
    z_unemplrate "County unemployment rate, std."
global coeflabels $coeflabels ///
    z_consimmi "County concerns immigration, std."
global coeflabels $coeflabels z_cdu "County share CDU/CSU voters, std."

global table_opt collabels(none) constant not wide
global table_opt $table_opt starlevels(+ 0.1 * 0.05 ** 0.01)
global table_opt $table_opt compress nogaps nodepvars
global table_opt $table_opt refcat(2.asyl_req_stat ///
    "Status of the asylum request (Ref.: approved): ", nolabel)
global table_opt $table_opt indicate("Survey year fe = *.syear" ///
    "Survey sample fe = *.msample" ///
    "Federal State fe = *.nuts1_first" ///
    "Country of origin (aggregated) fe = *.immigroup_nat")
global table_opt $table_opt scalars(N groups M_mi e_r2 e_r2a)
global table_opt $table_opt sfmt(%9.0f %9.0f %9.0f %9.4f %9.4f)

program define _mi_addstats
    quietly {
        capture soepdrop e_*
        args estimates
        est des `estimates'
        mi xeq: `r(cmdline)'; gen e_r2 = e(r2); gen e_r2a = e(r2_a)
        foreach var of varlist e_* {
            mi est, post: mean `var'
            local `var' = _b[`var']
            estadd scalar `var' = ``var'', replace: `estimates'
        }
        soepdrop e_*
        capture soepdrop groups
        bysort pid: generate groups = _n
        count if groups == 1
        local groups = r(N)
        display `groups'
        estadd scalar groups = `groups', replace: `estimates'
    }
end

capture soepdrop m_0011p
eststo m_0011p: mi estimate, post dots ///
    saving($mydata/msuemer/tab05_germ, replace) esample(m_0011p): ///
    reg paid_work $controls_fv ///
    c.stay_dur c.z_ratio_courseoport ///
    c.german_additive ///
    [pweight=weight_p], vce(cluster pid)
_mi_addstats m_0011p
capture soepdrop m_0012p
eststo m_0012p: mi estimate, post dots ///
    saving($mydata/msuemer/tab05_crs, replace) esample(m_0012p): ///
    reg paid_work $controls_fv ///
    c.stay_dur c.z_ratio_courseoport ///
    i.int_course_finished ///
    [pweight=weight_p], vce(cluster pid)
_mi_addstats m_0012p
capture soepdrop m_0013p
eststo m_0013p: mi estimate, post dots ///
    saving($mydata/msuemer/tab05_cert, replace) esample(m_0013p): ///
    reg paid_work $controls_fv ///
    c.stay_dur c.z_ratio_courseoport ///
    i.germ_cert_any ///
    [pweight=weight_p], vce(cluster pid)
_mi_addstats m_0013p
capture soepdrop m_0014p
eststo m_0014p: mi estimate, post dots ///
    saving($mydata/msuemer/tab05_cont, replace) esample(m_0014p): ///
    reg paid_work $controls_fv ///
    c.stay_dur c.z_ratio_courseoport ///
    c.time_germ ///
    [pweight=weight_p], vce(cluster pid)
_mi_addstats m_0014p
capture soepdrop m_0015p
eststo m_0015p: mi estimate, post dots ///
    saving($mydata/msuemer/tab05_all_crs, replace) esample(m_0015p): ///
    reg paid_work $controls_fv ///
    c.stay_dur c.z_ratio_courseoport ///
    c.german_additive i.int_course_finished c.time_germ ///
    [pweight=weight_p], vce(cluster pid)
_mi_addstats m_0015p
capture soepdrop m_0016p
eststo m_0016p: mi estimate, post dots ///
    saving($mydata/msuemer/tab05_all_crt, replace) esample(m_0016p): ///
    reg paid_work $controls_fv ///
    c.stay_dur c.z_ratio_courseoport ///
    c.german_additive i.germ_cert_any c.time_germ ///
    [pweight=weight_p], vce(cluster pid)
_mi_addstats m_0016p
esttab m_0011p m_0012p m_0013p m_0014p m_0015p m_0016p, ///
    title("COURSE SUPPLY AND EMPLOYMENT: intermediaries, p.p.") ///
    order(z_ratio_courseoport stay_dur german_additive ///
        1.int_course_finished 1.germ_cert_any time_germ _cons) ///
    coeflabels(z_ratio_courseoport "County supply of courses, std." ///
        stay_dur "Duration of stay, in months (/12)" ///
        german_additive "German language proficiency" ///
        1.int_course_finished "Completion of an integration course" ///
        1.germ_cert_any "Obtainment of a language certificate" ///
        time_germ "Contact frequency with Germans" ///
        $coeflabels _cons "Constant") ///
    $table_opt nobaselevels varwidth(34) ///
    transform(@*100 100) b(%9.2f) se(%9.2f)

display "23C ok"

